import type { AnalysisReport, Finding } from "../core/types.js";
import { findingLocation } from "./shared.js";

export function markdownReport(report: AnalysisReport): string {
  const lines = [
    "# Skillcheck report",
    "",
    `Analyzed **${report.summary.skills}** skill${report.summary.skills === 1 ? "" : "s"}: ` +
      `**${report.summary.errors}** errors, **${report.summary.warnings}** warnings, ` +
      `and **${report.summary.infos}** informational findings.`,
    ""
  ];

  if (report.globalFindings.length > 0) {
    lines.push("## Project findings", "");
    for (const finding of report.globalFindings) appendFinding(lines, finding);
  }

  for (const result of report.results) {
    lines.push(
      `## ${escapeMarkdown(result.name ?? result.directory)} - ${result.score}/100 (${result.grade})`,
      ""
    );
    lines.push(
      `\`${result.skillFile}\` | ${result.metrics.fileCount} files | ` +
        `approximately ${result.metrics.estimatedTokens} context tokens`,
      ""
    );
    if (result.findings.length === 0) {
      lines.push("No findings.", "");
    } else {
      for (const finding of result.findings) appendFinding(lines, finding);
    }
  }

  lines.push(`_Generated by Skillcheck ${report.tool.version}._`, "");
  return lines.join("\n");
}

function appendFinding(lines: string[], finding: Finding): void {
  lines.push(
    `### ${severityLabel(finding.severity)} ${escapeMarkdown(finding.title)}`,
    "",
    `${finding.message}`,
    "",
    `- Rule: \`${finding.ruleId}\``,
    `- Location: \`${findingLocation(finding)}\``
  );
  if (finding.evidence) lines.push(`- Evidence: \`${escapeCode(finding.evidence)}\``);
  if (finding.help) lines.push(`- Fix: ${finding.help}`);
  lines.push("");
}

function severityLabel(severity: Finding["severity"]): string {
  return { error: "[ERROR]", warning: "[WARNING]", info: "[INFO]" }[severity];
}

function escapeMarkdown(value: string): string {
  return value.replaceAll(/([\\`*_{}[\]()#+.!|>])/gu, "\\$1");
}

function escapeCode(value: string): string {
  return value.replaceAll("`", "\\`");
}
